name: Checkmarx One Scan
on:
  push:
    branches:
      - angular16
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: KB_GHA_SCS_JShop
          cx_tenant: DP_WP_ACCOUNT
          base_uri: https://eu.ast.checkmarx.net/ #I am using EU cluster
          cx_client_id: KB_GHA
          cx_client_secret: rt3zq1iLpb4dyoD2JbrFCWT2cda5kAb7
          additional_params: "--scan-types scs --scs-engines scorecard --scs-repo-url http://github.com/Kabacx/Juiceshop-public --scs-repo-token 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 --debug"
