name: Checkmarx One Scan
on:
  push:
    branches:
      - angular16
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: KB_GHA_SCS_JShop
          cx_tenant: DP_WP_ACCOUNT
          base_uri: https://eu.ast.checkmarx.net/ 
          cx_client_id: KB_GHA
          cx_client_secret: KcHdj182hq46OGHBDFm9Fm4Wcvn4GmQ7
          GITHUB_TOKEN : ${{ secrets.GH_TOKEN }}
          additional_params: "--debug --scan-types scs --scs-engines scorecard --scs-repo-url http://github.com/Kabacx/Juiceshop-public.git --scs-repo-token '${{ secrets.GH_TOKEN }}'" 
